language: ruby
cache: bundler
bundler_args: --without documentation production
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
  - rbx-20mode
  - 2.1.0-preview1
matrix:
  allow_failures:
    - rvm:
      - 2.1.0-preview1
script:
  - rake spec