language: ruby
cache: bundler
bundler_args: --without documentation production
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm:
      - rbx-19mode
      - 2.1.0
script:
  - rake spec